"""添加用户成绩相关字段

Revision ID: 13dadc09313c
Revises: bbf7fc2993c4
Create Date: 2025-09-30 22:35:23.694704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dadc09313c'
down_revision = 'bbf7fc2993c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('academic_talent_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comprehensive_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('final_score')
        batch_op.drop_column('comprehensive_score')
        batch_op.drop_column('academic_talent_score')
        batch_op.drop_column('academic_score')

    # ### end Alembic commands ###
