"""添加学生成绩细分项字段

Revision ID: af2f7135e893
Revises: a7daddf94d60
Create Date: 2025-10-02 17:56:25.897297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2f7135e893'
down_revision = 'a7daddf94d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('patent_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('competition_national_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('competition_provincial_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('csp_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('innovation_project_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('honor_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('social_work_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volunteer_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volunteer_hours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('volunteer_hours')
        batch_op.drop_column('volunteer_score')
        batch_op.drop_column('social_work_score')
        batch_op.drop_column('honor_score')
        batch_op.drop_column('innovation_project_score')
        batch_op.drop_column('csp_score')
        batch_op.drop_column('competition_provincial_score')
        batch_op.drop_column('competition_national_score')
        batch_op.drop_column('patent_score')
        batch_op.drop_column('paper_score')

    # ### end Alembic commands ###
